Lesson4 (4/18) 12:50
satou-001133/java_T pull request #1
Opened 2024-04-18 04:38 UTC by satou-001133

【概要】
4章実力確認問題のコーディングが完了しました。

【内容】
①保険契約者の情報を出力し、出力の最後に遅延利息が発生している人数を出力する。
②商品/単価/支払金額を3回入力し、支払金額の不足有無を出力、最後に不足の合計を出力。
①・②ともに入力値はString配列に格納。

【テスト仕様書】
[4章_テスト仕様書 (4月23日).xlsx](https://github.com/satou-001133/java_T/files/15074226/4._.4.23.xlsx)

2024-04-18 04:50 UTC, satou-001133 commented
ブランチ仕切り直しました。
ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_T/blob/main/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-21 04:06 UTC, yu-it-engineer requested changes
レビューしました！

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +
余分な改行を削除してください！
また全体的にインデントを見直してください！

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        if (found) {
利息の遅延が発生している人の人数をカウントしてください。
2名固定ではないはずです。
設定する値を修正しても動くようにしてください。

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +            System.out.println("再度入力してください。");
遅延している人が見つからなかった場合に再入力のメッセージを出力するのは処理としてよくわかりません！
見直してください！

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +			if (shortage < 0) {
条件は合っていますか？
マイナスなら過不足なしですか？

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson5/Lesson5_1.java
> +    public double getTotalPrice() {
メソッドにはJavaDocをつけてください！

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson5/Lesson5_1.java
> +        System.out.println("金額を入力してください。");
インデントがおかしいです！
全体的に見直してください！

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson5/Lesson5_1.java
> +            	} else {
このelseは何のelseでしょうか？

2024-04-21 04:06 UTC, yu-it-engineer commented on HelloWorld/src/Lesson5/Lesson5_2.java
> + */
問題に則していません！
メインクラスとは別に計算クラスを作成してください！

2024-04-23 04:16 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +
改行・インデントを見直しました🙇
インデントは必ず改行位置に配置するようにしたいと思いますが、こちらで認識は合っていますでしょうか？

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 04:17 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        if (found) {
利息発生者の人数をカウントできるよう、zcount（int z)を設定しました。
ご確認の程、よろしくお願いいたします🙇

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 04:20 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +            System.out.println("再度入力してください。");
中村・田島・小澤・大西
の4名は条件で入っていますが、仮に条件に含まれていない、
"佐藤"が入力されると、対象（条件）の契約者を入力してもらうよう指示を出していますが、こちらは不要でしょうか？？

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 04:21 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +			if (shortage < 0) {
条件が誤っていたため、再度確認し修正いたしました。
ご確認の程、よろしくお願いいたします🙇
インデントについても、修正させていただきました。

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_2.java

2024-04-23 04:28 UTC, yu-it-engineer requested changes
レビューしました！

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +	 */
インデントがずれています！

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +            if (inputName.equals(name[i]))
if文は
if () {
} else {
}
としましょう！

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        {
for () {

}

としましょう！

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +                found = true; // 契約者該当
foundは何に使っていますか？

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        }
この問題は1つのループのみで可能です！

2024-04-23 04:28 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +		for (int i = 0; i < 3; i++) //3回繰り返す
この問題は1つのループで可能です！
ループは多くなるとその分処理が遅くなります！

2024-04-23 05:19 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +	 */
何度も大変失礼いたしました🙇
インデント修正いたしました！

インデントの位置について、調べてはいるものの、正直よく理解していません(^_^;)
https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 05:20 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +            if (inputName.equals(name[i]))
if文でのインデント位置承知しました！

ご確認の程、よろしくお願いいたします🙇


https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 05:20 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        {
for文のインデントの位置についても、承知しました！

ご確認の程、よろしくお願いいたします🙏


https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 05:22 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +                found = true; // 契約者該当
結論間違えです🙇

さらに上のコードでの契約者名で使用し、その流れで一応記載していました！
金額には不要のため削除させていただきました。

ご確認の程よろしくお願いいたします！

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 05:23 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        }
承知しました！
for (int i = 0; i < 1; i++) {
こちらで修正し、一回のループにさせていただきました！


https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

2024-04-23 05:25 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +		for (int i = 0; i < 3; i++) //3回繰り返す
こちらも、
for (int i = 0; i < 1; i++) 
これにし、一回のループにさせていただきました！
問題には、
⚫︎商品/単価/支払金額を3回入力し、支払金額の不足有無を出力。
と記載されていますが、これでもループは一回で大丈夫なのでしょうか？？

ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_2.java

2024-04-23 05:48 UTC, yu-it-engineer requested changes
レビューしました！

2024-04-23 05:48 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +	 */
クラスは合っています！
それに合わせてください！

2024-04-23 05:48 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_1.java
> +        }
for文が1つでいけます！

2024-04-23 05:48 UTC, yu-it-engineer commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +		for (int i = 0; i < 1; i++)
こちらもfor文1つでいけます！

2024-04-23 09:09 UTC, satou-0113 commented on HelloWorld/src/Lesson4/Lesson4_2.java
> +		for (int i = 0; i < 1; i++)
修正させていただきました！
ご指摘いただいた箇所を修正し、またテスト仕様書もこのコメントの下部に添付させていただきました！
お手数おかけしますが、
ご確認の程よろしくお願いいたします🙇

【Lesson4_1】
⚫︎インデントを調節
⚫︎for文を一つにまとめました。
https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

【Lesson4_2】
⚫︎for文を一つにまとめました。
https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

【テスト仕様書】
[4章_テスト仕様書 (4月23日).xlsx](https://github.com/satou-001133/java_T/files/15074263/4._.4.23.xlsx)

2024-04-23 14:07 UTC, satou-0113 commented
修正させていただきました！
ご指摘いただいた箇所を修正し、またテスト仕様書もこのコメントの下部に添付させていただきました！
お手数おかけしますが、
ご確認の程よろしくお願いいたします🙇

【Lesson4_1】
⚫︎インデントを調節
⚫︎for文を一つにまとめました。
https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

【Lesson4_2】
⚫︎for文を一つにまとめました。
https://github.com/satou-001133/java_T/blob/java-4-training/HelloWorld/src/Lesson4/Lesson4_1.java

【テスト仕様書】
[4章_テスト仕様書 (4月23日).xlsx](https://github.com/satou-001133/java_T/files/15074263/4._.4.23.xlsx)

2024-05-02 12:52 UTC, closed without merging

2024-05-02 12:52 UTC, satou-001133 commented
テスト